Adding TVOS target
BottleRocketStudios/iOS-Scotty pull request #22
Opened 2019-01-08 21:44 UTC by Specialist17

2019-01-08 21:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/BottleRocketStudios/iOS-Scotty?pullRequest=22) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/BottleRocketStudios/iOS-Scotty?pullRequest=22) before we can accept your contribution.<br/><hr/>**Fernando Arocho** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/BottleRocketStudios/iOS-Scotty?pullRequest=22) it.</sub>

2019-01-08 23:01 UTC, earlgaspard commented on Examples/Scotty-tvOSExample/AppDelegate.swift
> +
can remove this blank line

2019-01-08 23:02 UTC, earlgaspard commented on Examples/Scotty-tvOSExample/AppDelegate.swift
> +    func applicationWillResignActive(_ application: UIApplication) {
the methods that are not used can be removed. this is similar to how the iOS Example in Scotty looks

2019-01-08 23:35 UTC, earlgaspard commented
The pod spec needs to be updated to a new version - maybe 2.1.0 ?
Also, I think a deployment target needs to be added: `s.tvos.deployment_target = '9.0'`

2019-01-08 23:36 UTC, earlgaspard commented
Going to need updates to the README.md and CHANGELOG.md

2019-01-09 00:13 UTC, wmcginty requested changes

2019-01-09 00:13 UTC, wmcginty commented on Examples/Scotty-tvOSExample/Routing/Routable+App.swift
> +import Scotty_tvOS
Ideally we can tweak the module name to just be Scotty as well- Hyperspace does this for example.

2019-01-09 00:13 UTC, wmcginty commented on Examples/Scotty-tvOSExample/Routing/URL+RouteConvertible.swift
> +//  Scotty-iOS
We will want to make sure the comment in the headers are uniform - Scotty-tvOSExample

2019-01-09 17:51 UTC, tylermilner requested changes

2019-01-09 17:51 UTC, tylermilner commented on Examples/Scotty-tvOSExample/Routing/Routable+App.swift
> +                    DispatchQueue.main.asyncAfter(deadline: .now() + 1.0) {
Is there a reason to keep this dispatch async in here? It looks like it was copied from the iOS example, but I would advocate for cleaning it up if we can so we don't imply that you need to use it when using Scotty.

2019-01-09 17:51 UTC, tylermilner commented on Examples/Scotty-tvOSExample/Routing/Routable+App.swift
> +//
This class looks to be identical to the existing one in the iOS example. Could we create a top-level `Examples/Common` folder that we stick this in and then tell Xcode to include it in both the iOS example and tvOS example targets? That way we don't have a bunch of duplicated example code that will likely be a pain to maintain and update across all of the examples. We'd probably need to update the module name for the tvOS target first, as @wmcginty suggested below.

2019-01-09 17:51 UTC, tylermilner commented on Examples/Scotty-tvOSExample/Routing/RouteController+App.swift
> +//
Similar comment to above about extracting this into a shared `Examples/Common` folder and then making it a member of both tvOS and iOS targets.

2019-01-09 17:51 UTC, tylermilner commented on Examples/Scotty-tvOSExample/Routing/URL+RouteConvertible.swift
> +//
Similar comment to above about extracting this into a shared Examples/Common folder and then making it a member of both tvOS and iOS targets.

2019-01-09 17:51 UTC, tylermilner commented on Examples/Scotty-tvOSExample/View Controllers/LeftViewController.swift
> +//
Similar comment to above about extracting this into a shared Examples/Common folder and then making it a member of both tvOS and iOS targets. I see this is named `LeftViewController`, while the one in the iOS example is just named `ViewController.swift` so we'd need to rename it.

2019-01-09 17:51 UTC, tylermilner commented on Examples/Scotty-tvOSExample/View Controllers/MiddleViewController.swift
> +//
Similar comment to above about extracting this into a shared Examples/Common folder and then making it a member of both tvOS and iOS targets (named `OtherViewController.swift` in the iOS example).

2019-01-09 17:51 UTC, tylermilner commented on Examples/Scotty-tvOSExample/View Controllers/RightViewController.swift
> +//
Similar comment to above about extracting this into a shared Examples/Common folder and then making it a member of both tvOS and iOS targets (named `LastViewController.swift` in the iOS example).

2019-01-09 17:51 UTC, tylermilner commented on Sources/Scotty/Route.swift
> +import UIKit
Is this necessary? I don't think the current version has any trouble compiling with the Foundation import.

2019-01-09 17:51 UTC, tylermilner commented on Sources/Scotty/RouteController.swift
> +import UIKit
Similar to above comment about existing Foundation import.

2019-01-09 20:44 UTC, wmcginty commented on Examples/Scotty-tvOSExample/Routing/Routable+App.swift
> +                    DispatchQueue.main.asyncAfter(deadline: .now() + 1.0) {
There's no need for it. I arbitrarily added it when I first created the sample project. It can be removed.

2023-05-19 02:56 UTC, closed without merging