Added Swift Package Manager Support
BottleRocketStudios/iOS-Scotty pull request #31
Opened 2019-09-06 19:10 UTC by JobsIsMyHomeboy

Added SPM Support and tested against my fork on Xcode 11. Using the `swift build` command to test the build with travis.

2019-09-06 19:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/BottleRocketStudios/iOS-Scotty?pullRequest=31) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/BottleRocketStudios/iOS-Scotty?pullRequest=31) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/BottleRocketStudios/iOS-Scotty?pullRequest=31) it.</sub>

2019-09-06 21:57 UTC, wmcginty requested changes

2019-09-06 21:57 UTC, wmcginty commented on CHANGELOG.md
> +[Brian Miller](https://gitthub.com/jobsismyhomeboy)
Minor typo - GitHub :)

2019-09-09 11:26 UTC, JobsIsMyHomeboy commented on CHANGELOG.md
> +[Brian Miller](https://gitthub.com/jobsismyhomeboy)
Fixed.

2019-09-09 15:59 UTC, tylermilner approved these changes

2019-10-04 18:51 UTC, wmcginty approved these changes

2019-10-04 18:51 UTC, merged